apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-staticapp.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "81"
      port: 81
      targetPort: 80
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
