apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-staticapp.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-todoapp.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/reactjs-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - image: evandjefie/my-static-portfolio:1.0.0
          name: app
          ports:
            - containerPort: 80
              hostPort: 81
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
